var fs=require("fs");
var dest="C:/COWIDev/Github/IfcComparison/IfcComparison/Models/IfcComparerObjects.cs";
var L=[];function a(s){L.push(s===undefined?"":s);}
a("using IfcComparison.Logging;");
a("using IfcComparison.ViewModels;");
a("using Microsoft.Extensions.Logging;");
a("using System;");
a("using System.Collections.Generic;");
a("using System.Linq;");
a("using System.Threading.Tasks;");
a("using Xbim.Common;");
a("using Xbim.Ifc;");
a("using Xbim.Ifc4.Interfaces;");
a("using Xbim.Ifc4.UtilityResource;");
a("");
a("namespace IfcComparison.Models");
a("{");
a("    public class IfcComparerObjects");
a("    {");
a("        private readonly ILogger<IfcComparerObjects> _logger;");
a("        public IfcStore IfcComparerModel { get; }");
a("        public IfcEntity Entity { get; }");
a("        public List<IfcObjectStorage> IfcStorageObjects { get; private set; } = new List<IfcObjectStorage>();");
a("");
a("        private IfcComparerObjects(IfcStore ifcModel, IfcEntity entity)");
a("        {");
a("            IfcComparerModel = ifcModel;");
a("            Entity = entity;");
a("            _logger = LoggingService.CreateLogger<IfcComparerObjects>();");
a("            _logger.LogDebug(\"IfcComparerObjects created for entity: {EntityType}\", entity?.Entity ?? \"Unknown\");");
a("        }");
a("");
a("        public static async Task<IfcComparerObjects> CreateAsync(IfcStore ifcModel, IfcEntity entity)");
a("        {");
a("            var logger = LoggingService.CreateLogger(typeof(IfcComparerObjects).FullName);");
a("            logger.LogInformation(\"Creating IfcComparerObjects for entity type: {EntityType}\", entity?.Entity ?? \"Unknown\");");
a("            var instance = new IfcComparerObjects(ifcModel, entity);");
a("            await instance.InitializeIfcObjectsOptimized();");
a("            return instance;");
a("        }");
a("");
a("        /// <summary>");
a("        /// OPTIMIZED: Single-pass initialization using forward lookups.");
a("        ///");
a("        /// Issue #1 fix: The comparisonOperator is searched across ALL property sets on");
a("        /// each object (not only requiredPSetNames). A one-time per-object scan");
a("        /// finds the pset and caches the value in ObjectComparisonIdCache.");
a("        /// A warning is logged and output to console when the operator cannot be found.");
a("        /// </summary>");
a("        private async Task InitializeIfcObjectsOptimized()");
a("        {");
a("            _logger.LogInformation(\"Initializing IFC objects for {EntityType} using OPTIMIZED single-pass method\", Entity?.Entity ?? \"Unknown\");");
a("            try");
a("            {");
a("                var requiredPSetNames = Entity?.IfcPropertySets ?? new List<string>();");
a("                var targetType = IfcTools.GetInterfaceType(Entity?.Entity);");
a("                var comparisonOperator = Entity?.ComparisonOperator ?? string.Empty;");
a("                var comparisonMethod = Entity?.ComparisonMethod ?? string.Empty;");
a("                bool useOperatorLookup = comparisonMethod != nameof(IfcComparison.Enumerations.ComparisonEnumeration.Identifier)");
a("                                         && !string.IsNullOrEmpty(comparisonOperator);");
a("");
a("                _logger.LogDebug(\"Looking for property sets: {PSets}, Target type: {Type}\",");
a("                    string.Join(\", \", requiredPSetNames), targetType?.Name ?? \"null\");");
a("");
a("                // Pass 1: Build object -> ALL PSets map (any PSet name, entity-filtered).");
a("                // Scan every relationship so comparisonOperator can be found in any PSet.");
a("                var allObjectPSets = new Dictionary<IIfcObject, List<IIfcPropertySet>>();");
a("                var allRelationships = IfcComparerModel.Instances.OfType<IIfcRelDefinesByProperties>().ToList();");
a("                _logger.LogDebug(\"Processing {Count} relationships in single pass\", allRelationships.Count);");
a("");
a("                foreach (var rel in allRelationships)");
a("                {");
a("                    var relPSets = rel.RelatingPropertyDefinition.PropertySetDefinitions");
a("                        .OfType<IIfcPropertySet>().ToList();");
a("                    if (!relPSets.Any()) continue;");
a("");
a("                    foreach (var obj in rel.RelatedObjects");
a("                        .Where(o => targetType == null || targetType.IsInstanceOfType(o))");
a("                        .OfType<IIfcObject>())");
a("                    {");
a("                        if (!allObjectPSets.ContainsKey(obj))");
a("                            allObjectPSets[obj] = new List<IIfcPropertySet>();");
a("                        foreach (var ps in relPSets)");
a("                            if (!allObjectPSets[obj].Contains(ps))");
a("                                allObjectPSets[obj].Add(ps);");
a("                    }");
a("                }");
a("");
a("                // Pass 2: Resolve comparisonId from ANY PSet on each object.");
a("                var objectComparisonIdCache = new Dictionary<IIfcObject, string>();");
a("                if (useOperatorLookup)");
a("                {");
a("                    int notFoundCount = 0;");
a("                    foreach (var kvp in allObjectPSets)");
a("                    {");
a("                        var obj = kvp.Key;");
a("                        string comparisonValue = null;");
a("                        string foundInPSet = null;");
a("                        foreach (var pset in kvp.Value)");
a("                        {");
a("                            var prop = pset.HasProperties");
a("                                .OfType<IIfcPropertySingleValue>()");
a("                                .FirstOrDefault(p => p.Name.ToString().Contains(comparisonOperator));");
a("                            if (prop?.NominalValue != null)");
a("                            {");
a("                                comparisonValue = prop.NominalValue.ToString();");
a("                                foundInPSet = pset.Name?.ToString();");
a("                                break;");
a("                            }");
a("                        }");
a("                        if (comparisonValue != null)");
a("                        {");
a("                            objectComparisonIdCache[obj] = comparisonValue;");
a("                            _logger.LogDebug(\"ComparisonOperator found in PSet for object\");");
a("                        }");
a("                        else");
a("                        {");
a("                            notFoundCount++;");
a("                        }");
a("                    }");
a("                    if (notFoundCount > 0)");
a("                    {");
a("                        var msg = string.Format("+
"'\"ComparisonOperator \x27{0}\x27 could not be found in any property set for {1} object(s) of type \x27{2}\x27. Those objects will be skipped.\",'"+"'comparisonOperator, notFoundCount, Entity?.Entity);");
